BackOffices/Controllers/PageController.cs
using BackOffices.CustomFilters;
using Security.Foundation.Data.Interfaces;
using Security.Foundation.Data.Models;
using Security.Foundation.Data.WrapModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BackOffices.Controllers
{
    public class PageController : Controller
    {
        //
        // GET: /Page/
        private readonly IPageImpl _iPageImpl;
        private readonly IMenuImpl _iMenuImpl;
        private readonly IMenuPageImpl _iMenuPageImpl;
        private readonly IPageRoleImpl _iPageRoleImpl;
        private readonly IRoleImpl _iRoleImpl;

        private readonly IPagePermissionImpl _iPagePermissionImpl;
        private readonly IPagePermissionRoleImpl _iPagePermissionRoleImpl;

        public PageController(IPageImpl iPageImpl, IMenuImpl iMenuImpl, IMenuPageImpl iMenuPageImpl, 
            IPageRoleImpl iPageRoleImpl, IRoleImpl iRoleImpl, 
            IPagePermissionImpl iPagePermissionImpl, IPagePermissionRoleImpl iPagePermissionRoleImpl)
        {
            _iPageImpl = iPageImpl;
            _iMenuImpl = iMenuImpl;
            _iMenuPageImpl = iMenuPageImpl;
            _iPageRoleImpl = iPageRoleImpl;
            _iRoleImpl = iRoleImpl;
            _iPagePermissionImpl = iPagePermissionImpl;
            _iPagePermissionRoleImpl = iPagePermissionRoleImpl;
        }

       [ValidateUserRoles]
        public ActionResult Index()
        {
            try
            {
                var wrapPages = new List<WrapPage>();
                var parentPages = _iPageImpl.GetByParentID(0).OrderBy(m => m.PageName).ToList();
                foreach (var item in parentPages)
                {
                    var wrapPage = new WrapPage
                    {
                        Page = item,
                        SubPages = _iPageImpl.GetByParentID(item.ID).OrderBy(sp => sp.PageName).ToList()
                    };
                    wrapPages.Add(wrapPage);
                }

                return View(wrapPages);
            }
            catch (Exception ex)
            {
                TempData["MessageError"] = ex.InnerException;
            }

            return View(new List<WrapPage>());
        }

       [ValidateUserRoles]
       public ActionResult Add()
       {
           ViewBag.ParentPages = _iPageImpl.GetByParentID(0);
           ViewBag.Menus = _iMenuImpl.All();
           ViewBag.Roles = _iRoleImpl.All();
           return View("Edit", new Page());
       }
       [ValidateUserRoles]
       public ActionResult Edit(int pageid)
       {

           try
           {
               var _page = _iPageImpl.GetById(pageid);
               ViewBag.ParentPages = _iPageImpl.GetByParentID(0);
               ViewBag.PageRoles = _iPageRoleImpl.GetByPageID(pageid).ToList();
               ViewBag.Menus = _iMenuImpl.All();
               ViewBag.Roles = _iRoleImpl.All();
               if (_page == null)
               {
                   ViewBag.MenuPages = _iMenuPageImpl.GetMenuPageByPageID(pageid).ToList();
                   TempData["MessageError"] = "Không tồn tại trang này.";
               }
               else
               {
                   ViewBag.MenuPages = _iMenuPageImpl.GetMenuPageByPageID(pageid).ToList();
                   return View(_page);
               }
           }
           catch (Exception ex)
           {
               TempData["MessageError"] = ex.InnerException;
           }

           return View(new Page());
       }


       [HttpPost]
       public ActionResult Edit(Page model, int slPage, string[] tagmenu_selected, string[] tagrole_selected)
       {
           try
           {

               if (model.ID > 0)
               {
                   //Edit Page
                   var _page = _iPageImpl.GetById(model.ID);
                   _page.PageName = model.PageName;

                   if (model.PageURL.Substring(model.PageURL.Length - 1) == "/")
                   {
                       _page.PageURL = model.PageURL.Substring(0, model.PageURL.LastIndexOf("/"));
                   }
                   else
                   {
                       _page.PageURL = model.PageURL;
                   }

                   _page.ParentPageID = slPage;
                   _iPageImpl.Update(_page);
                   if (_page.ID > 0)
                   {
                       //edit menupage follow tag
                       _iMenuPageImpl.DeleteAllByPageID(_page.ID);
                       if (tagmenu_selected != null)
                       {
                           foreach (var menuid in tagmenu_selected)
                           {
                               var _menu = _iMenuImpl.GetById(Convert.ToInt32(menuid));
                               if (_menu != null)
                               {
                                   MenuPage _MenuPage = new MenuPage();
                                   _MenuPage.MenuID = _menu.ID;
                                   _MenuPage.MenuName = _menu.MenuName;
                                   _MenuPage.PageID = _page.ID;
                                   _MenuPage.PageName = _page.PageName;
                                   _MenuPage.PageURL = _page.PageURL;
                                   _iMenuPageImpl.Add(_MenuPage);
                               }
                           }
                       }
                       //#################################################
                       //tag role ################################
                       _iPageRoleImpl.DeleteAllByPageID(model.ID);
                       if (tagrole_selected != null)
                       {
                           //tag_selected = tag_selected.Union(tag_selected).ToArray();

                           foreach (var item in tagrole_selected)
                           {
                               string[] _strSplit = item.Split(new char[] { '|' });
                               PageRole _PageRole = new PageRole();
                               _PageRole.PageID = _page.ID;
                               _PageRole.PageName = _page.PageName;
                               _PageRole.RoleID = Convert.ToInt32(_strSplit[0]);
                               _PageRole.RoleName = _strSplit[1];
                               _iPageRoleImpl.Add(_PageRole);
                           }
                       }
                       //#########################################


                       TempData["MessageSuccess"] = "Thay đổi trang \"" + _page.PageName + "\" thành công.";
                       return RedirectToAction("Edit", new { pageid = _page.ID });
                   }

               }
               else
               {
                   //Add Page
                   Page _page = new Page();
                   _page.PageName = model.PageName;

                   if (model.PageURL.Substring(model.PageURL.Length - 1) == "/")
                   {
                       _page.PageURL = model.PageURL.Substring(0, model.PageURL.LastIndexOf("/"));
                   }
                   else
                   {
                       _page.PageURL = model.PageURL;
                   }


                   _page.ParentPageID = slPage;
                   _iPageImpl.Add(_page);
                   if (_page.ID > 0)
                   {
                       TempData["MessageSuccess"] = "Thêm mới trang \"" + _page.PageName + "\" thành công.";

                       //add menupage follow tag #########################
                       if (tagmenu_selected != null)
                       {
                           foreach (var menuid in tagmenu_selected)
                           {
                               var _menu = _iMenuImpl.GetById(Convert.ToInt32(menuid));
                               if (_menu != null)
                               {
                                   MenuPage _MenuPage = new MenuPage();
                                   _MenuPage.MenuID = _menu.ID;
                                   _MenuPage.MenuName = _menu.MenuName;
                                   _MenuPage.PageID = _page.ID;
                                   _MenuPage.PageName = _page.PageName;
                                   _MenuPage.PageURL = _page.PageURL;
                                   _iMenuPageImpl.Add(_MenuPage);
                               }
                           }
                       }
                       //############################################

                       //tag role ################################
                       if (tagrole_selected != null)
                       {
                           //tag_selected = tag_selected.Union(tag_selected).ToArray();

                           foreach (var item in tagrole_selected)
                           {
                               string[] _strSplit = item.Split(new char[] { '|' });
                               PageRole _PageRole = new PageRole();
                               _PageRole.PageID = _page.ID;
                               _PageRole.PageName = _page.PageName;
                               _PageRole.RoleID = Convert.ToInt32(_strSplit[0]);
                               _PageRole.RoleName = _strSplit[1];
                               _iPageRoleImpl.Add(_PageRole);
                           }
                       }
                       //#########################################


                       return RedirectToAction("Add");
                   }
               }


             


           }
           catch (Exception ex)
           {
               TempData["MessageError"] = ex.InnerException;
           }

BackOffices/Views/Page/Edit.cshtml
@model Security.Foundation.Data.Models.Page
@{

    if (Model.ID > 0)
    {
        ViewBag.Title = "EDIT PAGE";
    }
    else
    {

        ViewBag.Title = "ADD PAGE";
    }

    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Javascript{
    <script type="text/javascript">

        $(document).ready(function () {
            jQuery.validator.messages.required = "";
            $("#form-page").validate({
                invalidHandler: function (form, validator) {
                    var errors = validator.numberOfInvalids();
                    if (errors) {
                        var message = errors == 1
                        ? '1 error. Input correct info.'
                        : '' + errors + ' errors. Input correct info.';
                        $("#mws-validate-error").html(message).show();
                        $('label.error').hide();
                    } else {
                        $("#mws-validate-error").hide();
                    }
                },
                onkeyup: false,
                messages: {
                    PageName: {
                        required: "Page Name do not empty."
                    },
                    PageURL: {
                        required: "URL Page do not empty."
                    }
                }
            });

       


        });


    </script>
}

@section Breadcrumb{
    <div class="row">
        <div class="col-lg-12">
            <ul class="breadcrumb">
                <li><a href="/"></a><i class="fa fa-home"></i></li>
                <li><a href="/Page">PAGES</a></li>
                <li class="active">@ViewBag.Title</li>
            </ul>
        </div>
    </div>
}

<div class="row">
    <div class="col-lg-12">
        <div class="widget-container fluid-height clearfix">
            <div class="heading" style="text-transform:uppercase;">
                <i class="fa fa-bars"></i>@ViewBag.Title
            </div>
            <div class="widget-content padded">
                @using (Html.BeginForm("Edit", "Page", FormMethod.Post, new { @class = "mws-form", id = "form-page", novalidate = "novalidate" }))
                {
                    @Html.HiddenFor(p => p.ID)
                    @Html.HiddenFor(p => p.ParentPageID)
                    <fieldset>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>PAGE NAME</label>
                                    @Html.TextBoxFor(p => p.PageName, new { @class = "form-control required" })
                                </div>
                                <div class="form-group">
                                    <label>URL PAGE</label>
                                    @Html.TextBoxFor(p => p.PageURL, new { @class = "form-control required" })
                                </div>
                                <div class="form-group">
                                    <label>BELONG PAGE</label>
                                    <select id="slPage" name="slPage" class="select2able">
                                        <option value="0">---------------- PARENT PAGE -----------------</option>
                                        @if (ViewBag.ParentPages != null)
                                        {
                                            foreach (var item in ViewBag.ParentPages)
                                            {
                                                <option value="@item.ID" @(Model.ParentPageID == item.ID ? "selected" : "")>@item.PageName</option>
                                            }
                                        }

                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>MENU</label>
                                    <select class="select2able" multiple="" name="tagmenu_selected">
                                        @if (ViewBag.Menus != null)
                                        {
                                            if (ViewBag.MenuPages != null)
                                            {
                                                foreach (var item in ViewBag.Menus)
                                                {
                                                    <option value="@item.ID" @(((List<Security.Foundation.Data.Models.MenuPage>)ViewBag.MenuPages).FirstOrDefault(ac => ac.MenuName == item.MenuName) != null ? "selected" : "")>@item.MenuName</option>
                                                }
                                            }
                                            else
                                            {
                                                foreach (var item in ViewBag.Menus)
                                                {
                                                    <option value="@item.ID">@item.MenuName</option>
                                                }
                                            }


                                        }
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>ROLES</label>
                                    <select class="select2able" multiple="" name="tagrole_selected">
                                        @if (ViewBag.Roles != null)
                                        {
                                            if (ViewBag.PageRoles != null)
                                            {
                                                foreach (var item in ViewBag.Roles)
                                                {
                                                    <option value="@item.ID|@item.RoleName" @(((List<Security.Foundation.Data.Models.PageRole>)ViewBag.PageRoles).FirstOrDefault(ac => ac.RoleName == item.RoleName) != null ? "selected" : "")>@item.RoleName</option>
                                                }
                                            }
                                            else
                                            {
                                                foreach (var item in ViewBag.Roles)
                                                {
                                                    <option value="@item.ID|@item.RoleName">@item.RoleName</option>
                                                }
                                            }


                                        }
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label></label>
                                    <button class="btn btn-primary" type="submit" style="float:right;">SUBMIT</button>
                                </div>

                            </div>
                        </div>
                    </fieldset>
                }

            </div>
        </div>
    </div>
</div>

BackOffices/Views/Page/Index.cshtml
@{
    ViewBag.Title = "Page list";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<Security.Foundation.Data.WrapModels.WrapPage>

@section Breadcrumb{
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <ul class="breadcrumb">
                <li><a href="/"></a><i class="fa fa-home"></i></li>
                <li class="active">Page list</li>
            </ul>
        </div>
    </div>
}

@section Javascript{
    <script src="/javascripts/jquery.dataTables.min.js" type="text/javascript"></script>

    <script type="text/javascript">
        
    


    $(document).ready(function () {

            var oTable = $("#table-pages").dataTable({
                "sPaginationType": "full_numbers",
                "iDisplayLength": 25,
                aoColumnDefs: [
                  {
                      bSortable: true,
                      aTargets: [-2, -1]
                  }
                ],
                "oLanguage": {
                    "sSearch": "Search:",
                    "sLengthMenu": "Show _MENU_ result",
                    "sInfoEmpty": "Show 0 to 0 of 0 result",
                    "sInfo": "Show _START_ to _END_ of _TOTAL_ result",
                    "oPaginate": {
                        "sFirst": "First",
                        "sLast": "Last",
                        "sNext": "Next",
                        "sPrevious": "Previous"

                    }
                }
            });
            var nEditing = null;
            oTable.fnSort([[1, 'asc']]);

     




            $('#table-pages').on('click', 'a.delete-row', function (e) {
                e.preventDefault();

                var nRow = $(this).parents('tr')[0];

                if (confirm("Are you want to delete?") == true) {
                    var jqTds = $('>td', nRow);
                    var pageid = $(jqTds[1]).attr('pageid');

                    
                    $.post('/Page/Delete', {
                        pageid: pageid
                    }, function (data) {
                        if (parseInt(data) > 0) {

                            alert(data);
                        }
                        else {
                            alert(data);
                        }
                    });

                    oTable.fnDeleteRow(nRow);
                }



            });

         




        });
    </script>
}

<div class="row">
    <!-- Hover Row Table -->
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="widget-container fluid-height clearfix">
            <div class="heading" style="text-transform:uppercase;">
                <i class="fa fa-table"></i>Page list
                <a id="add-row" href="/Page/Add" class="btn btn-sm btn-primary-outline pull-right"><i class="fa fa-plus"></i>Add page</a>
            </div>
            <div class="widget-content padded clearfix">
                @if (Model != null)
                {
                    int count = 0;
                    <div class="table-responsive">
                        <table class="table table-hover" id="table-pages">
                            <thead>
                                <tr>
                                    <th class="check-header hidden-xs"><label><input id="checkAll" name="checkAll" type="checkbox"><span></span></label></th>
                                    <th><strong>Page name</strong></th>
                                    <th class="hidden-xs"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="check hidden-xs">
                                            <label><input name="optionsRadios1" type="checkbox" value="option1"><span></span></label>
                                        </td>
                                        <td pageid="@(item.Page.ID)">@item.Page.PageName</td>
                                        <td style="text-align:right;">
                                            <div class="btn-group">
                                                <button @(item.SubPages.Count() > 0 ? "" : "disabled") data-toggle="dropdown" class="btn btn-warning dropdown-toggle"><i class="fa fa-bars"></i><span class="caret"></span></button>
                                                <ul class="dropdown-menu" style="text-align:left;">
                                                    @foreach (var _page in item.SubPages)
                                                    {
                                                        <li>
                                                            <a href="/Page/Edit?PageID=@(_page.ID)"><i class="fa fa-file-o"></i>@_page.PageName</a>
                                                        </li>
                                                    }


                                                </ul>
                                            </div>
                                            <a class="edit-row btn btn-primary" href="/Page/Edit?PageID=@(item.Page.ID)"><i class="fa fa-edit"></i>Edit</a>
                                            <a class="delete-row btn btn-danger" href=""><i class="fa fa-trash-o"></i>Delete</a>
                                        </td>
                                    </tr>
                                                    count++;
                                }
                            </tbody>
                        </table>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- end Hover Row Table --><!-- Responsive Table -->
    <!-- end Responsive Table -->
</div>